[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = [ 'neomru.vim' ]

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_fixers = {
    \ 'ruby': [ 'rubocop' ],
    \ 'python': [ 'pycodestyle' ],
    \ 'javascript': [ 'eslint' ],
    \ 'css': [ 'stylelint' ],
    \ 'scss': [ 'stylelint' ],
    \ 'typescript': [ 'prettier' ],
    \ 'less': [ 'prettier' ],
    \ 'json': [ 'prettier' ],
    \ 'markdown': [ 'prettier' ],
\}
let g:ale_linters = {
    \ 'ruby': [ 'rubocop' ],
    \ 'python': [ 'pyflakes', 'black', 'isort' ],
    \ 'javascript': [ 'eslint', 'eslint-plugin-vue' ],
    \ 'tex': [ 'textlint' ],
    \ 'markdown': [ 'write-good' ],
    \ 'css': [ 'stylelint' ],
    \ 'scss': [ 'stylelint' ],
    \ 'html': [ 'htmlhint' ],
\ }
let g:ale_lint_on_enter = 0
let g:ale_lint_on_save = 0
let g:ale_lint_on_text_changed = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '❌'
let g:ale_sign_warning = '⚠️'
"highlight clear ALEErrorSign
"highlight clear ALEWarningSign
let g:ale_statusline_format = [ 'E%d', 'W%d', 'ok' ]
let g:ale_set_loclist = 0
let g:ale_set_quickfix = 0
let g:ale_open_list = 0
let g:ale_keep_list_window_open = 0
let g:ale_fix_on_save = 0
let g:ale_echo_msg_format = '[%linter%] %code: %%s'

"let g:ale_javascript_prettier_options = '--single-quote --trailing-comma es5'

"nmap <silent> <C-n> <Plug>(ale_next_wrap)
nmap <silent> <C-N> <Plug>(ale_next)
nmap <silent> <C-P> <Plug>(ale_previous)
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
let g:webdevicons_enable = 1
let g:webdevicons_enable_nerdtree = 0
let g:webdevicons_conceal_nerdtree_brackets = 1
let g:WebDevIconsNerdTreeAfterGlyphPadding = ' '

let g:WebDevIconsUnicodeDecorateFolderNodes = 1
let g:DevIconsEnableFoldersOpenClose = 1
let g:WebDevIconsUnicodeByteOrderMarkerDefaultSymbol = ''
let g:WebDevIconsUnicodeDecorateFolderNodesDefaultSymbol = ''
let g:DevIconsDefaultFolderOpenSymbol = ''

let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols = {
      \ 'fcgi':     '',
      \ 'perl':     '',
      \ 'sqlite':   '',
      \ 'tt':       '',
      \ 'vue':      '',
      \ 'html':     '',
      \ 'css':      '',
      \ 'md':       '',
      \ 'txt':      ''
      \ }
'''

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = [ 'context_filetype.vim', 'vim-textobj-user' ]

[[plugins]] # for <Plug>(textobj-precious-i) in vim-precious
repo = 'kana/vim-textobj-user'

[[plugins]]
repo     = 'airblade/vim-rooter'
hook_add = '''
let g:rooter_silent_chdir = 1
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
" # hide --INSERT--
set noshowmode

let g:lightline = {
    \ 'colorscheme': 'wombat',
    \ 'active': {
    \   'left': [ [ 'mode', 'paste' ],
    \             [ 'readonly', 'filename', 'modified' ],
    \             [ 'linter_checking', 'linter_errors', 'linter_warnings', 'linter_ok' ]
    \   ]
    \ },
    \ 'inactive': {
    \   'left': [ [ 'pending' ], ],
    \   'right': [],
    \ },
    \ 'tabline': {
    \   'left': [ [ 'buffers' ],
    \             [ 'separator' ],
    \             [ 'bufferbefore', 'buffercurrent', 'bufferafter' ],
    \   ],
    \   'right': []
    \ },
    \ 'component_expand': {
    \   'linter_checking': 'lightline#ale#checking',
    \   'linter_warnings': 'lightline#ale#warnings',
    \   'linter_errors': 'lightline#ale#errors',
    \   'linter_ok': 'lightline#ale#ok',
    \   'buffers': 'lightline#bufferline#buffers',
    \   'buffercurrent': 'lightline#buffer#buffercurrent',
    \   'bufferbefore': 'lightline#buffer#bufferbefore',
    \   'bufferafter': 'lightline#buffer#bufferafter',
    \ },
    \ 'component_type': {
    \   'linter_checking': 'left',
    \   'linter_warnings': 'warning',
    \   'linter_errors': 'error',
    \   'linter_ok': 'left',
    \   'buffercurrent': 'tabsel',
    \   'bufferbefore': 'raw',
    \   'bufferafter': 'raw',
    \   'buffers': 'tabsel',
    \ },
    \ 'component_function': {
    \   'bufferinfo': 'lightline#buffer#bufferinfo',
    \   'pending': 'lightline#Pending',
    \ },
    \ 'separator': { 'left': ' ', 'right': ' ' },
    \ 'subseparator': { 'left': '|', 'right': '|' },
\ }

function! LightlineTabFilename(n) abort
  let buflist = tabpagebuflist(a:n)
  let winnr = tabpagewinnr(a:n)
  let _ = pathshorten(expand('#'.buflist[winnr - 1].':f'))
  return _ !=# '' ? _ : '[No Name]'
endfunction

function! LightlineFilename()
  return ('' != LightlineReadonly() ? LightlineReadonly() . ' ' : '') .
       \ ('' != expand('%:t') ? expand('%:t') : '[No Name]') .
       \ ('' != LightlineModified() ? ' ' . LightlineModified() : '')
endfunction
'''

[[plugins]]
repo = 'maximbaz/lightline-ale'
depends = [ 'lightline.vim', 'ale' ]

[[plugins]]
repo = 'mengelbrecht/lightline-bufferline'
depends = [ 'lightline.vim' ]

[[plugins]]
repo = 'ghifarit53/tokyonight-vim'

