hook_add = '''
" Python
let g:python_highlight_all = 1

" Update filetype.
autocmd MyAutoCmd BufWritePost * nested
\ if &l:filetype ==# '' || exists('b:ftdetect')
\ |   unlet! b:ftdetect
\ |   filetype detect
\ | endif

'''

[ftplugin]

_ = '''
  " Disable automatically insert comment.
  setl formatoptions-=ro
  setl formatoptions+=mMBl

  " Disable auto wrap.
  if &l:textwidth != 70 && &filetype !=# 'help'
    setlocal textwidth=0
  endif

  if !&l:modifiable
    setlocal nofoldenable
    setlocal foldcolumn=0
    setlocal colorcolumn=
  endif
'''

python = '''
" Indent settings.
setlocal foldmethod=indent
setlocal softtabstop=4
setlocal shiftwidth=4
setlocal textwidth=80
setlocal smarttab
setlocal expandtab
setlocal nosmartindent
'''

html = '''
setlocal includeexpr=substitute(v:fname,'^\\/','','')
setlocal path+=./;/
'''

go = '''
highlight default link goErr WarningMsg
match goErr /\<err\>/
'''

vim = '''
if line('$') > 1000
  syntax sync minlines=200
endif

setlocal foldmethod=indent
setlocal shiftwidth=2 softtabstop=2
setlocal iskeyword+=:,#
'''

qfreplace = 'setlocal nofoldenable'

toml = 'syntax sync minlines=500'

help = '''
setlocal iskeyword+=:
setlocal iskeyword+=#
setlocal iskeyword+=-
'''

ruby = '''
setlocal iskeyword+=!
setlocal iskeyword+=?
setlocal omnifunc=
setlocal shiftwidth=2 softtabstop=2 tabstop=2
'''

yaml = '''
setlocal tabstop=2
setlocal softtabstop=2
setlocal shiftwidth=2
'''

typescriptreact = '''
" dark red
hi tsxTagName guifg=#E06C75
hi tsxComponentName guifg=#E06C75
hi tsxCloseComponentName guifg=#E06C75

" orange
hi tsxCloseString guifg=#F99575
hi tsxCloseTag guifg=#F99575
hi tsxCloseTagName guifg=#F99575
hi tsxAttributeBraces guifg=#F99575
hi tsxEqual guifg=#F99575

" yellow
hi tsxAttrib guifg=#F8BD7F cterm=italic

" light-grey
hi tsxTypeBraces guifg=#999999
" dark-grey
hi tsxTypes guifg=#666666

hi ReactState guifg=#C176A7
hi ReactProps guifg=#D19A66
hi ApolloGraphQL guifg=#CB886B
hi Events ctermfg=204 guifg=#56B6C2
hi ReduxKeywords ctermfg=204 guifg=#C678DD
hi ReduxHooksKeywords ctermfg=204 guifg=#C176A7
hi WebBrowser ctermfg=204 guifg=#56B6C2
hi ReactLifeCycleMethods ctermfg=204 guifg=#D19A66
'''
